on:
  push:
    branches:
      - master
  release:
    types:
    - created

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - name: Publish
      if: success() && startsWith( github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
    - name: Package
      if: success() && startsWith( github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
      run: npm run package
    - name: Release
      uses: alexellis/upload-assets@0.2.2
      if: success() && startsWith( github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["./*.vsix"]'
    