on:
  push:
    tags:
      - 'v*'
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - run: npm install
    - name: Publish
      if: success() && startsWith( github.ref, 'refs/tags/')
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
    - name: Package
      if: success() && startsWith( github.ref, 'refs/tags/')
      run: npm run package
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: '*.vsix'
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
