on:
  push:
    tags:
      - 'v*'
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - name: Publish
      if: success() && startsWith( github.ref, 'refs/tags/')
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
    - name: Package
      if: success() && startsWith( github.ref, 'refs/tags/')
      run: npm run package
    - name: Release
      uses: alexellis/upload-assets@0.2.2
      if: success() && startsWith( github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["./*.vsix"]'
    